pipeline:
  name: canary-shop-ui
  identifier: canaryshopui
  projectIdentifier: Canary_Shop
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.GitHub_sbrooksharness
        repoName: canary-shop-ui
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and Push an image to Docker Registry_1
                  identifier: BuildandPushanimagetoDockerRegistry_1
                  spec:
                    connectorRef: org.sbrooksharnessdockerhub
                    repo: sbrooksharness/canary-shop-ui
                    tags:
                      - <+pipeline.executionId>
